#!/usr/bin/env python3
"""Regenerate ``lesson_index.toml`` from the actual packaged bytes.

Hashes are never hand-written. This reads the real files, computes their
digests, and writes the index — so the index cannot drift from the content it
claims to describe.

Run it after any change to a lesson TOML or asset::

    python scripts/generate_lesson_index.py

A content change invalidates existing review attestations. Regenerating the
index does not re-approve anything: the payload hash will change, every
attestation will stop matching, and the lesson will fail to load until the
affected reviews are actually redone. That is the intended behavior.
"""

import hashlib
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[1] / "src"))

from lerni.explore.catalog import lesson_payload_sha256, parse_lesson_toml  # noqa: E402

LESSONS = pathlib.Path(__file__).resolve().parents[1] / "src/lerni/explore/lessons"
MEDIA_TYPES = {".svg": "image/svg+xml"}


def main() -> int:
    lessons = sorted(p for p in LESSONS.glob("*.toml") if p.name != "lesson_index.toml")
    assets = sorted(LESSONS.glob("assets/*"))

    lines = ["# Generated by scripts/generate_lesson_index.py. Do not hand-edit.", ""]
    lines.append("schema_version = 1")

    for path in lessons:
        raw = path.read_bytes()
        lesson = parse_lesson_toml(raw.decode("utf-8"), origin=path.name)
        lines += [
            "",
            "[[lessons]]",
            f'lesson_id = "{lesson.id}"',
            f'resource_name = "{path.name}"',
            f'sha256 = "{hashlib.sha256(raw).hexdigest()}"',
            f'lesson_payload_sha256 = "{lesson_payload_sha256(lesson)}"',
        ]

    for path in assets:
        media_type = MEDIA_TYPES.get(path.suffix)
        if media_type is None:
            print(f"skipping unsupported asset {path.name}", file=sys.stderr)
            continue
        lines += [
            "",
            "[[assets]]",
            f'resource_name = "assets/{path.name}"',
            f'media_type = "{media_type}"',
            f'sha256 = "{hashlib.sha256(path.read_bytes()).hexdigest()}"',
        ]

    (LESSONS / "lesson_index.toml").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote lesson_index.toml: {len(lessons)} lesson(s), {len(assets)} asset(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
